version: '3.7'
services:
  playground:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/go/src/github.com/yyh-gl/go-playground
    command: ['sh', '-c', 'air -d']

  mysql:
    image: mysql
    ports:
      - '13306:3306'
    volumes:
      - ./db/migrations/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playground

  postgresql:
    image: postgres
    ports:
      - '15432:5432'
    volumes:
      - ./db/migrations/postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playground
