version: '3.7'
services:
  playground:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/yyh-gl/go-playground
    command: ['sh', '-c', 'air -d']
    depends_on:
      - db

  db:
    # mysql:8.0（M1 Macのためにダイジェストで指定）
    image: mysql@sha256:03306a1f248727ec979f61424c5fb5150e2c5fd2436f2561c5259b1258d6063c
    ports:
      - '13306:3306'
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: playground
