version: '3.7'
services:
  playground:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/playground
    command: ['sh', '-c', 'air -d']
#    depends_on:
#      - db
#
#  db:
#    image: mysql:latest
#    ports:
#      - '13306:3306'
#    volumes:
#      - ./docker/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql
